### ISSUE TITLE
Stable version of capsulahub

### ISSUE THREAD

**Issue by 95kach** [capsulajs/capsulahub#11]
## General description

As a developer, I want to have the possibility to use the capsulahub according to the documentation without any unexpected side effects.

I need to know from which version I can use capsulahub as a stable product.

CLI, documentation or examples of usage should be realistic and ready for use in production.

## Behavior

It should work.

**Comment by stephanebenayoun** [comment]
Being more specific will help.
We currently have this issue opened https://github.com/capsulajs/capsulahub/issues/5

If you have other pains using CapsulaHub right now please details them and they will be addressed if they are relevant.

**Comment by 95kach** [comment]
1. I have a configuration:

```javascript
// src/config.js
module.exports = {
  name: 'Exchange Backoffice',
  services: [
    {
      serviceName: 'RendererService',
      path: 'https://s3-eu-west-1.amazonaws.com/capsulajs/core/capsulahub-core-renderer/develop/index.js',
      definition: {
        serviceName: 'RendererService',
        methods: {
          renderLayouts: {
            asyncModel: 'requestResponse',
          },
          renderItems: {
            asyncModel: 'requestResponse',
          },
          renderItem: {
            asyncModel: 'requestResponse',
          },
        },
      },
      config: {},
    },
    {
      serviceName: 'CalendarService',
      path: 'https://exchange-backoffice-backend.s3-eu-west-1.amazonaws.com/feature/clean/calendar-service/service.js',
      definition: {
        serviceName: 'CalendarService',
        methods: {
          list: {
            asyncModel: 'requestResponse',
          },
        },
      },
      config: {},
    },
    {
      serviceName: 'ConfigurationService',
      path:
        'https://exchange-backoffice-backend.s3-eu-west-1.amazonaws.com/feature/clean/configuration-service/service.js',
      definition: {
        serviceName: 'ConfigurationService',
        methods: {
          createRepository: {
            asyncModel: 'requestResponse',
          },
          delete: {
            asyncModel: 'requestResponse',
          },
          entries: {
            asyncModel: 'requestResponse',
          },
          fetch: {
            asyncModel: 'requestResponse',
          },
          save: {
            asyncModel: 'requestResponse',
          },
        },
      },
      config: {
        token: 'fjfj',
        dispatcher: 'scalecube',
      },
    },
  ],
  components: {
    layouts: {},
    items: {
      root: {
        componentName: 'calendar-table',
        path:
          'https://exchange-backoffice-frontend.s3-eu-west-1.amazonaws.com/feature/fix_import/calendar-table/index.js',
        config: {},
      },
    },
  },
};
```

2. I run command `capsula-hub run -l src/config.js -p 3000`
3. I receive an error in the browser:
`Fetch API cannot load localhost:3000/configuration/workspace.json. URL scheme must be "http" or "https" for CORS request.`
`Uncaught (in promise) Error: Configuration repository workspace not found
    at ConfigurationServiceHttpFile.js:19`

**Comment by 95kach** [comment]
@stephanebenayoun @dmitriyslaym Added comments with details

**Comment by 95kach** [comment]
The problem that capsulahub tries to open config not from local file

**Comment by 95kach** [comment]
Deps: `"@capsulajs/capsula-hub": "0.0.8",`

**Comment by stephanebenayoun** [comment]
New version of CapsulaHub CLI will be available very soon. For this kind of issues please open a Bug report.

**Comment by stephanebenayoun** [comment]
The problem you describe is a bug we identified now, caused by update of workspace version that impacted the CLI by mistake. Anyway as I said before we will publish new version very soon.

**Comment by 95kach** [comment]
So ok, I will wait for the new version of CLI and will create the bug report if find this bug again in the new version of CLI
