### ISSUE TITLE
Make service path optional in Workspace configuration

### ISSUE THREAD

**Issue by vvpyshnenko** [capsulajs/capsulahub#26]
## General description
The current workspace configuration requires 'path' key for every using service:
```javascript
{
      "serviceName": "CalendarService",
      "path": "http://localhost:3000/packages/gateway-proxy/dist/service.js",
      "definition": {
        "serviceName": "CalendarService",
        "methods": {
          "list": { "asyncModel": "requestResponse" },
          "get": { "asyncModel": "requestResponse" },
          "create": { "asyncModel": "requestResponse" },
          "update": { "asyncModel": "requestResponse" }
        }
      },
      "config": {}
    }
```
This means that capsulahub should always load and inject service by itself. 

In exchange-backoffice application I don't need to load all services from CDN. I load only one service and in it bootsrap function I create rest of services and register them in workspace. In order to provide that I need to declare services without 'path' key like this:
```javascript
{
      "serviceName": "CalendarService",
      "definition": {
        "serviceName": "CalendarService",
        "methods": {
          "list": { "asyncModel": "requestResponse" },
          "get": { "asyncModel": "requestResponse" },
          "create": { "asyncModel": "requestResponse" },
          "update": { "asyncModel": "requestResponse" }
        }
      },
      "config": {}
    }
```  
and I expect capsulahub to put proxy for the service in workspace without loading service itself. So only change in API configuration is to make 'path' optional and only if it exist load service from the given path.

1. Is it backward compatible? - Yes
2. Adds new API - No
3. Changes existing API - Yes
4. Removes existing API - No

## Ready for implementation
- [ ] External dependencies have been resolved
- [ ] API has been approved
- [ ] Test cases have been prepared
- [ ] Discussed with Technical lead

## Definition of Done
- [ ] Maintainer review
- [ ] All tests are implemented 
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

**Comment by idanilt** [comment]
@stephanebenayoun 
I think all the fields in the config can be optional

**Comment by stephanebenayoun** [comment]
Will be handle in https://github.com/capsulajs/capsulahub/issues/27
