### ISSUE TITLE
Workspace should not fail on extension error

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub#5]
## General description

When using CapsulaHub, user provide his extensions that will be running inside the application. Currently, any error that occurs in any service or component will make the application stop working.

Expected behavior is that application will continue to run even if parts of it throw errors. Other parts should continue to work without being impacted by errors in the problematic extension.

This behavior should be true during the initialisation process and while using the application.

Trying to access an extension that throw error should result using the workspace should be rejected with a clear error message.

## Prerequisites
None.

## API
No changes in API.

## Technical consideration
When running the bootstrap function of each extension, Workspace should wrap it inside a try/catch block, so it won't affect other extensions and workspace.

When handling error in this try/catch block, we should provide to the user all information to debug this error and workspace should be able to reject any attempt to access the extension.

## Test cases

```gherkin
Scenario: An error with bootstrapping a service occurs after calling createWorkspace
    Given WorkspaceFactory instance with createWorkspace method
    And  Configuration for token 123 that includes service A and B and components 1 and 2
    And  Service A and service B include a bootstrap that calls registerService
    When I run createWorkspace method with token 123
    And  An error with bootstrapping a service occurs
    Then I expect workspace to be created
    And  a console log that bootstrapping of this service failed is displayed
    And  calling services method is rejected with an error message

Scenario: An error with bootstrapping a component occurs after calling createWorkspace
    Given WorkspaceFactory instance with createWorkspace method
    And  Configuration for token 123 that includes service A and B and components 1 and 2
    When I run createWorkspace method with token 123
    And  An error with bootstrapping a component occurs
    Then I expect workspace to be created
    And  a console log that bootstrapping of this component failed is displayed
    And  calling components method is rejected with an error message
```

## Ready for implementation
- [x] External dependencies have been resolved
- [ ] ~API has been approved~
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes

**Comment by stephanebenayoun** [comment]
Important to provide as much information as possible when there is an error (which extension, stack trace, etc.)
